@extends('developer.reference.menu')

@section('content')
    <h1>{{ $title }}</h1>
    <p class="lead-text">Creates one or more airtime orders</p>

    <div class="endpoint-box">
        <span class="endpoint-method get">POST</span>
        <span class="endpoint-url">{{ url('/') }}/api/v1/airtime-order</span>
    </div>

    <h2 id="request-parameters">Body Parameters</h2>

    <table class="params-table">
        <thead>
        <tr>
            <th>Parameter</th>
            <th>Type</th>
            <th>Required</th>
            <th>Description</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><span class="param-name">data</span></td>
            <td><span class="param-type">array</span></td>
            <td>required</td>
            <td>
                An array of airtime order objects. Each object represents one airtime order to be created.
            </td>
        </tr>
        <tr>
            <td><span class="param-name">data.*.external_reference</span></td>
            <td><span class="param-type">string</span></td>
            <td>required</td>
            <td>
                A unique reference generated by your system for tracking the order. This helps prevent duplicate processing and makes reconciliation easier.
            </td>
        </tr>
        <tr>
            <td><span class="param-name">data.*.operator_id</span></td>
            <td><span class="param-type">string</span></td>
            <td>required</td>
            <td>The ID of the airtime operator.</td>
        </tr>
        <tr>
            <td><span class="param-name">data.*.amount</span></td>
            <td><span class="param-type">numeric</span></td>
            <td>required</td>
            <td>The amount/value of each airtime .</td>
        </tr>

        <tr>
            <td><span class="param-name">data.*.phone</span></td>
            <td><span class="param-type">string</span></td>
            <td>required</td>
            <td>The phone number of the recipient.</td>
        </tr>
        <tr>
            <td><span class="param-name">data.*.phone_code</span></td>
            <td><span class="param-type">string</span></td>
            <td>required</td>
            <td>
                Recipient phone country code using the country ISO2 format, for example: US, NG, ZW.
            </td>
        </tr>
        </tbody>
    </table>

    <h2 id="example-request">Example Request</h2>

    <h3 id="create-gift-card-orders">Create airtime orders</h3>

    <div class="code-block-wrapper">
        <div class="code-block-header">
            <span class="code-block-title">cURL</span>
            <button class="code-copy-button">Copy</button>
        </div>
        <pre><code class="language-bash">curl -X POST {{ url('/') }}/api/v1/airtime-order \
  -H "Authorization: Bearer sk_live_your_api_key" \
  -H "Content-Type: application/json" \
  -d '{
    "data": [
      {
            "external_reference": "order-ref-001",
            "operator_id": "3e0e1d43-809c-4f36-b069-b7fe6ee2b6d4",
            "amount": "1000",
            "phone": "09072963268",
            "phone_code": "ng"
        },
        {
            "external_reference": "order-ref-002",
            "operator_id": "3e0e1d43-809c-4f36-b069-b7fe6ee2b6d4",
            "amount": "800",
            "phone": "09057550480",
            "phone_code": "ng"
        }
    ]
  }'</code></pre>
    </div>

    <div class="code-block-wrapper">
        <div class="code-block-header">
            <span class="code-block-title">PHP</span>
            <button class="code-copy-button">Copy</button>
        </div>
        <pre><code class="language-php">$client = new GuzzleHttp\Client([
    'base_uri' => '{{ url('/') }}/api/v1',
    'headers' => [
        'Authorization' => 'Bearer sk_live_your_api_key',
        'Content-Type' => 'application/json',
        'Accept' => 'application/json',
    ],
]);

$response = $client->post('/airtime-order', [
    'json' => [
        'data' => [
            [
                'external_reference' => 'order-ref-001',
                'operator_id' => '3e0e1d43-809c-4f36-b069-b7fe6ee2b6d4',
                'amount' => 1100,
                'phone' => '09057550480',
                'phone_code' => 'ng',
            ],
            [
                'external_reference' => 'order-ref-002',
                'operator_id' => '3e0e1d43-809c-4f36-b069-b7fe6ee2b6d4',
                'amount' => 1500,
                'phone' => '09057550480',
                'phone_code' => 'ng',
            ],
        ],
    ],
]);

$orders = json_decode($response->getBody(), true);</code></pre>
    </div>

    <div class="code-block-wrapper">
        <div class="code-block-header">
            <span class="code-block-title">JavaScript</span>
            <button class="code-copy-button">Copy</button>
        </div>
        <pre><code class="language-javascript">const response = await fetch('{{ url('/') }}/api/v1/airtime-order', {
  method: 'POST',
  headers: {
    'Authorization': 'Bearer sk_live_your_api_key',
    'Content-Type': 'application/json',
    'Accept': 'application/json'
  },
  body: JSON.stringify({
    data: [
      {
        external_reference: 'order-ref-001',
        operator_id: 'cf562d2a-826c-42f1-a19f-3de7fe6911c0',
        amount: 1100,
        phone: '09057550480',
        phone_code: 'ng',
      },
      {
        external_reference: 'order-ref-002',
        operator_id: 'd96096ad-1eff-4e38-afd0-7d02973d4b5f',
        amount: 2000,
        phone: '09057550480',
        phone_code: 'ng',
      }
    ]
  })
});

const orders = await response.json();</code></pre>
    </div>

    <h2 id="response">Response</h2>

    <div class="code-block-wrapper">
        <div class="code-block-header">
            <span class="code-block-title">200 OK</span>
            <button class="code-copy-button">Copy</button>
        </div>
        <pre><code class="language-json">{
   "message": "Payment successful, processing order",
    "status": "success",
    "data": {
        "id": "7c6f2ada-47be-4207-b177-b59b83973a5a",
        "currency": "USD",
        "amount": 1.49,
        "charge": 0,
        "total": 1.49,
        "status": "success",
        "mode": "test",
        "balance": {
            "old_balance": null,
            "new_balance": null
        },
        "orders": [
            {
                "external_reference": "0ccb1b7d-a81b-45e8-b68b-84d4540e565c",
                "operator": {
                    "id": "3e0e1d43-809c-4f36-b069-b7fe6ee2b6d4",
                    "name": "Airtel Nigeria",
                    "amount": 1000,
                    "currency": "NGN"
                },
                "payment": {
                    "currency": "USD",
                    "rate": 0.00082918739635158,
                    "amount": 0.83,
                    "charge": 0,
                    "sub_total": 0.83,
                    "total": 0.83
                },
                "customer": {
                    "phone": "+2349072963268",
                    "phone_code": "ng"
                }
            },
            {
                "external_reference": "6075cbeb-96b5-4dd3-8441-41f434c71ff1",
                "operator": {
                    "id": "3e0e1d43-809c-4f36-b069-b7fe6ee2b6d4",
                    "name": "Airtel Nigeria",
                    "amount": 800,
                    "currency": "NGN"
                },
                "payment": {
                    "currency": "USD",
                    "rate": 0.00082918739635158,
                    "amount": 0.66,
                    "charge": 0,
                    "sub_total": 0.66,
                    "total": 0.66
                },
                "customer": {
                    "phone": "+2349057550480",
                    "phone_code": "ng"
                }
            }
        ],
        "created_at": "2026-05-05T13:20:54.000000Z"
    }
}</code></pre>
    </div>
@endsection