<div class="tab-pane fade @if(route('admin.settings', ['type' => 'security'])==url()->current())show active @endif" id="tabs-icons-text-2" role="tabpanel" aria-labelledby="tabs-icons-text-2-tab">
    <div class="card mb-10">
        <div class="card-body">
            <form action="{{route('admin.settings.update', ['type' => '2fa'])}}" method="post">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        @if($admin->fa_status==0)
                        <div class="text-center mb-10">
                            <img src="{{$image}}" class="user-profile mb-10">
                            <input name="secret" type="hidden" value="{{$secret}}">
                            <h5 class="m-0 text-dark fw-bold fs-7">{{$secret}} <i class="bi bi-copy text-dark castro-copy fs-5" data-clipboard-text="{{$secret}}" title="{{__('Copy')}}"></i></h5>
                        </div>
                        @endif
                        <div class="fv-row mb-6 form-floating">
                            <input name="fa_pin" type="tel" minlength="6" maxlength="6" pattern="[0-9]+" class="form-control form-control-solid" value="{{old('fa_pin')}}" required>
                            <label class="form-label text-dark fs-7 mb-0" for="pin">{{__('Code')}}</label>
                            @error('fa_pin')
                            <span class="form-text text-danger">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-success btn-block" wire:loading.attr="disabled">
                                <span wire:loading.remove wire:target="secondSecurity">
                                    @if($admin->fa_status==0)
                                    {{__('Activate')}}
                                    @elseif($admin->fa_status==1)
                                    {{__('Disable')}}
                                    @endif
                                </span>
                                <span wire:loading wire:target="secondSecurity">{{__('Processing Request...')}}</span>
                            </button>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="bg-light px-6 py-5 mb-10 rounded">
                            <h5 class="mb-1 text-dark fw-bold">{{__('Two Factor Authentication')}}</h5>
                            <p class="mb-2 text-gray-800 fs-7">{{__('Two-factor authentication is a security measure used to safeguard your online accounts. When enabled, it requires you to enter not just your password but also a unique code. This code can be obtained through a mobile app. Even if someone manages to obtain your password, they cannot gain access without the accompanying code.')}}</p>

                            @if($admin->fa_status==0)
                            <span class="badge badge-pill badge-danger mb-3">{{__('Disabled')}}</span>
                            @else
                            <span class="badge badge-pill bg-whitelabel text-dark mb-3">{{__('Active')}}</span>
                            >@endif

                            <ul class="text-gray-800 fs-7">
                                <li class="d-flex align-items-center"><span class="bullet me-5 bg-success bullet-vertical"></span>{{__('Install an authentication app on your device. Any app that supports the Time-based One-Time Password (TOTP) protocol should work.')}}</li>
                                <li class="d-flex align-items-center"><span class="bullet me-5 bg-success bullet-vertical"></span>{{__('Use the authenticator app to scan the barcode below.')}}</li>
                                <li class="d-flex align-items-center"><span class="bullet me-5 bg-success bullet-vertical"></span>{{__('Enter the code generated by the authenticator app.')}}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="card mb-10">
        <div class="card-body">
            <h4 class="fw-bold fs-5 mb-6">{{__('Recaptcha')}}</h4>
            <form action="{{route('admin.settings.update', ['type' => 'recaptcha'])}}" method="post">
                @csrf
                <p class="fs-7 text-dark">{{__('Google Recaptcha V3, this will be enabled on registration and contact us page to prevent spamming and bots')}}</p>
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7">{{__('NOCAPTCHA SECRET')}}</label>
                    <input class="form-control form-control-solid" type="text" name="NOCAPTCHA_SECRET" value="{{$set->NOCAPTCHA_SECRET}}" required />
                    @error('NOCAPTCHA_SECRET')
                    <span class="form-text">{{$message}}</span>
                    @enderror
                </div>
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7">{{__('NOCAPTCHA SITEKEY')}}</label>
                    <input class="form-control form-control-solid" type="text" name="NOCAPTCHA_SITEKEY" value="{{$set->NOCAPTCHA_SITEKEY}}" required />
                    @error('NOCAPTCHA_SITEKEY')
                    <span class="form-text">{{$message}}</span>
                    @enderror
                </div>
                <div class="form-check form-check-custom form-check-solid mb-6">
                    <input class="form-check-input" type="checkbox" id="recaptcha" name="recaptcha" value="1" @if($set->recaptcha==1)checked @endif />
                    <label class="form-check-label" for="recaptcha">{{__('Recaptcha')}}</label>
                </div>
                <div class="text-start">
                    <button type="submit" class="btn btn-success me-3 my-2">{{__('Update')}}</a>
                </div>
            </form>
        </div>
    </div>
    <div class="card mb-10">
        <div class="card-body">
            <h4 class="fw-bold fs-5 mb-6">{{__('Banned email domains')}}</h4>
            <form action="{{route('admin.settings.update', ['type' => 'email_banned'])}}" method="post">
                @csrf
                <p class="fs-7 text-dark">{{__('Users will not be allowed to register.')}}</p>
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7">{{__('Email domains')}}</label>
                    <input class="form-control form-control-solid" type="text" name="email_banned" id="kt_tagify_1" value="{{$set->email_banned}}" required />
                    @error('email_banned')
                    <span class="form-text">{{$message}}</span>
                    @enderror
                </div>
                <div class="text-start">
                    <button type="submit" class="btn btn-success me-3 my-2">{{__('Update')}}</a>
                </div>
            </form>
        </div>
    </div>
    <div class="card mb-10">
        <div class="card-body">
            <h4 class="fw-bold fs-5 mb-6">{{__('Permissions')}}</h4>
            <form action="{{route('admin.settings.update', ['type' => 'permissions'])}}" method="post">
                @csrf
                <div class="form-check form-check-custom form-check-solid mb-6">
                    <input class="form-check-input" type="checkbox" id="registration" name="registration" value="1" @if($set->registration==1)checked @endif />
                    <label class="form-check-label" for="registration">{{__('Registration')}}</label>
                </div>
                <div class="form-check form-check-custom form-check-solid mb-6">
                    <input class="form-check-input" type="checkbox" id="maintenance" name="maintenance" value="1" @if($set->maintenance==1)checked @endif />
                    <label class="form-check-label" for="maintenance">{{__('Maintenance mode')}}</label>
                </div>
                <div class="form-check form-check-custom form-check-solid mb-6">
                    <input class="form-check-input" type="checkbox" id="email_verify" name="email_verify" value="1" @if($set->email_verify==1)checked @endif />
                    <label class="form-check-label" for="email_verify">{{__('Require Email Verification')}}</label>
                </div>
                <div class="text-start">
                    <button type="submit" class="btn btn-success me-3 my-2">{{__('Update')}}</a>
                </div>
            </form>
        </div>
    </div>
    <div class="card mb-10">
        <div class="card-body">
            <p class="text-dark fs-5 fw-bold">{{__('Change admin login credentials')}}</p>
            <form action="{{route('admin.settings.update', ['type' => 'security'])}}" method="post">
                @csrf
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7">{{__('Admin URL')}}</label>
                    <input class="form-control form-control-solid" type="text" name="admin_url" value="{{$set->admin_url}}" required />
                    @error('admin_url')
                    <span class="form-text">{{$message}}</span>
                    @enderror
                </div>
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7">{{__('Username')}}</label>
                    <input class="form-control form-control-solid" type="text" name="username" value="{{$admin->username}}" />
                    @error('username')
                    <span class="form-text">{{$message}}</span>
                    @enderror
                </div>
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7">{{__('Password')}}</label>
                    <input class="form-control form-control-solid" type="password" name="password" required />
                    @error('password')
                    <span class="form-text">{{$message}}</span>
                    @enderror
                </div>
                <div class="text-start">
                    <button type="submit" class="btn btn-success me-3 my-2">{{__('Update')}}</a>
                </div>
            </form>
        </div>
    </div>
    <div class="card mb-10">
        <div class="card-body">
            <p class="text-dark fs-5 fw-bold">{{__('Admin Recovery')}}</p>
            <form action="{{route('admin.settings.update', ['type' => 'settings'])}}" method="post">
                @csrf
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7">{{__('Recovery email')}}</label>
                    <input class="form-control form-control-solid" type="email" name="recovery_email" value="{{$set->recovery_email}}" />
                    @error('recovery_email')
                    <span class="form-text">{{$message}}</span>
                    @enderror
                </div>
                <div class="text-start">
                    <button type="submit" class="btn btn-success me-3 my-2">{{__('Update')}}</a>
                </div>
            </form>
        </div>
    </div>
</div>