<div class="tab-pane fade <?php if(route('admin.settings', ['type' => 'security'])==url()->current()): ?>show active <?php endif; ?>" id="tabs-icons-text-2" role="tabpanel" aria-labelledby="tabs-icons-text-2-tab">
    <div class="card mb-10">
        <div class="card-body">
            <form action="<?php echo e(route('admin.settings.update', ['type' => '2fa'])); ?>" method="post">
                <?php echo csrf_field(); ?>
                <div class="row">
                    <div class="col-md-6">
                        <?php if($admin->fa_status==0): ?>
                        <div class="text-center mb-10">
                            <img src="<?php echo e($image); ?>" class="user-profile mb-10">
                            <input name="secret" type="hidden" value="<?php echo e($secret); ?>">
                            <h5 class="m-0 text-dark fw-bold fs-7"><?php echo e($secret); ?> <i class="bi bi-copy text-dark castro-copy fs-5" data-clipboard-text="<?php echo e($secret); ?>" title="<?php echo e(__('Copy')); ?>"></i></h5>
                        </div>
                        <?php endif; ?>
                        <div class="fv-row mb-6 form-floating">
                            <input name="fa_pin" type="tel" minlength="6" maxlength="6" pattern="[0-9]+" class="form-control form-control-solid" value="<?php echo e(old('fa_pin')); ?>" required>
                            <label class="form-label text-dark fs-7 mb-0" for="pin"><?php echo e(__('Code')); ?></label>
                            <?php $__errorArgs = ['fa_pin'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                            <span class="form-text text-danger"><?php echo e($message); ?></span>
                            <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-success btn-block" wire:loading.attr="disabled">
                                <span wire:loading.remove wire:target="secondSecurity">
                                    <?php if($admin->fa_status==0): ?>
                                    <?php echo e(__('Activate')); ?>

                                    <?php elseif($admin->fa_status==1): ?>
                                    <?php echo e(__('Disable')); ?>

                                    <?php endif; ?>
                                </span>
                                <span wire:loading wire:target="secondSecurity"><?php echo e(__('Processing Request...')); ?></span>
                            </button>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="bg-light px-6 py-5 mb-10 rounded">
                            <h5 class="mb-1 text-dark fw-bold"><?php echo e(__('Two Factor Authentication')); ?></h5>
                            <p class="mb-2 text-gray-800 fs-7"><?php echo e(__('Two-factor authentication is a security measure used to safeguard your online accounts. When enabled, it requires you to enter not just your password but also a unique code. This code can be obtained through a mobile app. Even if someone manages to obtain your password, they cannot gain access without the accompanying code.')); ?></p>

                            <?php if($admin->fa_status==0): ?>
                            <span class="badge badge-pill badge-danger mb-3"><?php echo e(__('Disabled')); ?></span>
                            <?php else: ?>
                            <span class="badge badge-pill bg-whitelabel text-dark mb-3"><?php echo e(__('Active')); ?></span>
                            ><?php endif; ?>

                            <ul class="text-gray-800 fs-7">
                                <li class="d-flex align-items-center"><span class="bullet me-5 bg-success bullet-vertical"></span><?php echo e(__('Install an authentication app on your device. Any app that supports the Time-based One-Time Password (TOTP) protocol should work.')); ?></li>
                                <li class="d-flex align-items-center"><span class="bullet me-5 bg-success bullet-vertical"></span><?php echo e(__('Use the authenticator app to scan the barcode below.')); ?></li>
                                <li class="d-flex align-items-center"><span class="bullet me-5 bg-success bullet-vertical"></span><?php echo e(__('Enter the code generated by the authenticator app.')); ?></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="card mb-10">
        <div class="card-body">
            <h4 class="fw-bold fs-5 mb-6"><?php echo e(__('Recaptcha')); ?></h4>
            <form action="<?php echo e(route('admin.settings.update', ['type' => 'recaptcha'])); ?>" method="post">
                <?php echo csrf_field(); ?>
                <p class="fs-7 text-dark"><?php echo e(__('Google Recaptcha V3, this will be enabled on registration and contact us page to prevent spamming and bots')); ?></p>
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7"><?php echo e(__('NOCAPTCHA SECRET')); ?></label>
                    <input class="form-control form-control-solid" type="text" name="NOCAPTCHA_SECRET" value="<?php echo e($set->NOCAPTCHA_SECRET); ?>" required />
                    <?php $__errorArgs = ['NOCAPTCHA_SECRET'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                    <span class="form-text"><?php echo e($message); ?></span>
                    <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>
                </div>
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7"><?php echo e(__('NOCAPTCHA SITEKEY')); ?></label>
                    <input class="form-control form-control-solid" type="text" name="NOCAPTCHA_SITEKEY" value="<?php echo e($set->NOCAPTCHA_SITEKEY); ?>" required />
                    <?php $__errorArgs = ['NOCAPTCHA_SITEKEY'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                    <span class="form-text"><?php echo e($message); ?></span>
                    <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>
                </div>
                <div class="form-check form-check-custom form-check-solid mb-6">
                    <input class="form-check-input" type="checkbox" id="recaptcha" name="recaptcha" value="1" <?php if($set->recaptcha==1): ?>checked <?php endif; ?> />
                    <label class="form-check-label" for="recaptcha"><?php echo e(__('Recaptcha')); ?></label>
                </div>
                <div class="text-start">
                    <button type="submit" class="btn btn-success me-3 my-2"><?php echo e(__('Update')); ?></a>
                </div>
            </form>
        </div>
    </div>
    <div class="card mb-10">
        <div class="card-body">
            <h4 class="fw-bold fs-5 mb-6"><?php echo e(__('Banned email domains')); ?></h4>
            <form action="<?php echo e(route('admin.settings.update', ['type' => 'email_banned'])); ?>" method="post">
                <?php echo csrf_field(); ?>
                <p class="fs-7 text-dark"><?php echo e(__('Users will not be allowed to register.')); ?></p>
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7"><?php echo e(__('Email domains')); ?></label>
                    <input class="form-control form-control-solid" type="text" name="email_banned" id="kt_tagify_1" value="<?php echo e($set->email_banned); ?>" required />
                    <?php $__errorArgs = ['email_banned'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                    <span class="form-text"><?php echo e($message); ?></span>
                    <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>
                </div>
                <div class="text-start">
                    <button type="submit" class="btn btn-success me-3 my-2"><?php echo e(__('Update')); ?></a>
                </div>
            </form>
        </div>
    </div>
    <div class="card mb-10">
        <div class="card-body">
            <h4 class="fw-bold fs-5 mb-6"><?php echo e(__('Permissions')); ?></h4>
            <form action="<?php echo e(route('admin.settings.update', ['type' => 'permissions'])); ?>" method="post">
                <?php echo csrf_field(); ?>
                <div class="form-check form-check-custom form-check-solid mb-6">
                    <input class="form-check-input" type="checkbox" id="registration" name="registration" value="1" <?php if($set->registration==1): ?>checked <?php endif; ?> />
                    <label class="form-check-label" for="registration"><?php echo e(__('Registration')); ?></label>
                </div>
                <div class="form-check form-check-custom form-check-solid mb-6">
                    <input class="form-check-input" type="checkbox" id="maintenance" name="maintenance" value="1" <?php if($set->maintenance==1): ?>checked <?php endif; ?> />
                    <label class="form-check-label" for="maintenance"><?php echo e(__('Maintenance mode')); ?></label>
                </div>
                <div class="form-check form-check-custom form-check-solid mb-6">
                    <input class="form-check-input" type="checkbox" id="email_verify" name="email_verify" value="1" <?php if($set->email_verify==1): ?>checked <?php endif; ?> />
                    <label class="form-check-label" for="email_verify"><?php echo e(__('Require Email Verification')); ?></label>
                </div>
                <div class="text-start">
                    <button type="submit" class="btn btn-success me-3 my-2"><?php echo e(__('Update')); ?></a>
                </div>
            </form>
        </div>
    </div>
    <div class="card mb-10">
        <div class="card-body">
            <p class="text-dark fs-5 fw-bold"><?php echo e(__('Change admin login credentials')); ?></p>
            <form action="<?php echo e(route('admin.settings.update', ['type' => 'security'])); ?>" method="post">
                <?php echo csrf_field(); ?>
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7"><?php echo e(__('Admin URL')); ?></label>
                    <input class="form-control form-control-solid" type="text" name="admin_url" value="<?php echo e($set->admin_url); ?>" required />
                    <?php $__errorArgs = ['admin_url'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                    <span class="form-text"><?php echo e($message); ?></span>
                    <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>
                </div>
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7"><?php echo e(__('Username')); ?></label>
                    <input class="form-control form-control-solid" type="text" name="username" value="<?php echo e($admin->username); ?>" />
                    <?php $__errorArgs = ['username'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                    <span class="form-text"><?php echo e($message); ?></span>
                    <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>
                </div>
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7"><?php echo e(__('Password')); ?></label>
                    <input class="form-control form-control-solid" type="password" name="password" required />
                    <?php $__errorArgs = ['password'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                    <span class="form-text"><?php echo e($message); ?></span>
                    <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>
                </div>
                <div class="text-start">
                    <button type="submit" class="btn btn-success me-3 my-2"><?php echo e(__('Update')); ?></a>
                </div>
            </form>
        </div>
    </div>
    <div class="card mb-10">
        <div class="card-body">
            <p class="text-dark fs-5 fw-bold"><?php echo e(__('Admin Recovery')); ?></p>
            <form action="<?php echo e(route('admin.settings.update', ['type' => 'settings'])); ?>" method="post">
                <?php echo csrf_field(); ?>
                <div class="fv-row mb-6">
                    <label class="form-label text-dark fs-7"><?php echo e(__('Recovery email')); ?></label>
                    <input class="form-control form-control-solid" type="email" name="recovery_email" value="<?php echo e($set->recovery_email); ?>" />
                    <?php $__errorArgs = ['recovery_email'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                    <span class="form-text"><?php echo e($message); ?></span>
                    <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>
                </div>
                <div class="text-start">
                    <button type="submit" class="btn btn-success me-3 my-2"><?php echo e(__('Update')); ?></a>
                </div>
            </form>
        </div>
    </div>
</div><?php /**PATH /Applications/MAMP/htdocs/axora/resources/views/partials/admin/security.blade.php ENDPATH**/ ?>