<?php
return [
    'nameToLocale' => [
        'english' => 'en',
        'french' => 'fr',
        'spanish' => 'es',
        'german' => 'de',
        'italian' => 'it',
        'portuguese' => 'pt',
        'dutch' => 'nl',
        'russian' => 'ru',
        'chinese' => 'zh',
        'japanese' => 'ja',
        'arabic' => 'ar',
        'korean' => 'ko',
        'hindi' => 'hi',
        'swahili' => 'sw',
        'greek' => 'el',
        'turkish' => 'tr',
        'swedish' => 'sv',
        'norwegian' => 'no',
        'danish' => 'da',
        'finnish' => 'fi',
        'polish' => 'pl',
        'hungarian' => 'hu',
        'czech' => 'cs',
        'slovak' => 'sk',
        'romanian' => 'ro',
        'bulgarian' => 'bg',
        'ukrainian' => 'uk',
        'croatian' => 'hr',
        'serbian' => 'sr',
        'slovenian' => 'sl',
        'macedonian' => 'mk',
        'latvian' => 'lv',
        'estonian' => 'et',
        'lithuanian' => 'lt',
        'maltese' => 'mt',
        'icelandic' => 'is',
        'luxembourgish' => 'lb',
        'albanian' => 'sq',
        'belarusian' => 'be',
        'georgian' => 'ka',
        'armenian' => 'hy',
        'kazakh' => 'kk',
        'uzbek' => 'uz',
        'tajik' => 'tg',
        'turkmen' => 'tk',
        'kyrgyz' => 'ky',
        'mongolian' => 'mn',
        'nepali' => 'ne',
        'sinhala' => 'si',
        'bengali' => 'bn',
        'urdu' => 'ur',
        'gujarati' => 'gu',
        'punjabi' => 'pa',
        'marathi' => 'mr',
        'telugu' => 'te',
        'tamil' => 'ta',
        'malayalam' => 'ml',
        'kannada' => 'kn',
        'odia' => 'or',
        'assamese' => 'as',
        'bodo' => 'brx',
        'dogri' => 'doi',
        'kashmiri' => 'ks',
        'konkani' => 'kok',
        'manipuri' => 'mni',
        'maithili' => 'mai',
        'nepal bhasa' => 'new',
        'sanskrit' => 'sa',
        'santali' => 'sat',
        'sindhi' => 'sd',
        'urdu' => 'ur',
        'tibetan' => 'bo',
        'dzongkha' => 'dz',
        'burmese' => 'my',
        'khmer' => 'km',
        'lao' => 'lo',
        'thai' => 'th',
        'vietnamese' => 'vi',
        'filipino' => 'fil',
        'indonesian' => 'id',
        'malay' => 'ms',
        'amharic' => 'am',
        'tigrinya' => 'ti',
        'somali' => 'so',
        'swahili' => 'sw',
        'yoruba' => 'yo',
        'igbo' => 'ig',
        'hausa' => 'ha',
        'zulu' => 'zu',
        'xhosa' => 'xh',
        'sesotho' => 'st',
        'southern sotho' => 'st',
        'tsonga' => 'ts',
        'venda' => 've',
        'ndebele' => 'nr',
        'shona' => 'sn',
        'chichewa' => 'ny',
        'kinyarwanda' => 'rw',
        'kirundi' => 'rn',
        'kikuyu' => 'ki',
        'luo' => 'luo',
        'kinyamwezi' => 'rwk',
        'chaga' => 'caf',
        'gomero' => 'ngo',
        'nyakyusa-ngonde' => 'ny',
        'rundi' => 'rw',
        'rwanda' => 'rw',
        'rwa' => 'rw',
        'kaguru' => 'kki',
        'kamba' => 'kam',
        'makonde' => 'kde',
        'pare' => 'pare',
        'samburu' => 'saq',
        'bena' => 'bez',
        'nilotic' => 'lwo',
        'lwo' => 'lwo',
        'west nilotic' => 'kwk',
        'kwakiutl' => 'kwk',
        'kwk' => 'kwk',
        'haida' => 'hai',
        'hai' => 'hai'
    ],
    'countryToLocale' => [
        'AD' => 'ca',  // Andorra -> Catalan
        'AE' => 'ar',  // United Arab Emirates -> Arabic
        'AF' => 'ps',  // Afghanistan -> Pashto
        'AG' => 'en',  // Antigua and Barbuda -> English
        'AI' => 'en',  // Anguilla -> English
        'AL' => 'sq',  // Albania -> Albanian
        'AM' => 'hy',  // Armenia -> Armenian
        'AO' => 'pt',  // Angola -> Portuguese
        'AQ' => 'en',  // Antarctica -> English
        'AR' => 'es',  // Argentina -> Spanish
        'AS' => 'en',  // American Samoa -> English
        'AT' => 'de',  // Austria -> German
        'AU' => 'en',  // Australia -> English
        'AW' => 'nl',  // Aruba -> Dutch
        'AX' => 'sv',  // Åland Islands -> Swedish
        'AZ' => 'az',  // Azerbaijan -> Azerbaijani
        'BA' => 'bs',  // Bosnia and Herzegovina -> Bosnian
        'BB' => 'en',  // Barbados -> English
        'BD' => 'bn',  // Bangladesh -> Bengali
        'BE' => 'nl',  // Belgium -> Dutch
        'BF' => 'fr',  // Burkina Faso -> French
        'BG' => 'bg',  // Bulgaria -> Bulgarian
        'BH' => 'ar',  // Bahrain -> Arabic
        'BI' => 'rn',  // Burundi -> Kirundi
        'BJ' => 'fr',  // Benin -> French
        'BL' => 'fr',  // Saint Barthélemy -> French
        'BM' => 'en',  // Bermuda -> English
        'BN' => 'ms',  // Brunei Darussalam -> Malay
        'BO' => 'es',  // Bolivia -> Spanish
        'BQ' => 'nl',  // Bonaire, Sint Eustatius and Saba -> Dutch
        'BR' => 'pt',  // Brazil -> Portuguese
        'BS' => 'en',  // Bahamas -> English
        'BT' => 'dz',  // Bhutan -> Dzongkha
        'BV' => 'en',  // Bouvet Island -> English
        'BW' => 'en',  // Botswana -> English
        'BY' => 'be',  // Belarus -> Belarusian
        'BZ' => 'en',  // Belize -> English
        'CA' => 'en',  // Canada -> English
        'CC' => 'en',  // Cocos (Keeling) Islands -> English
        'CD' => 'fr',  // Democratic Republic of the Congo -> French
        'CF' => 'fr',  // Central African Republic -> French
        'CG' => 'fr',  // Republic of the Congo -> French
        'CH' => 'de',  // Switzerland -> German
        'CI' => 'fr',  // Côte d'Ivoire -> French
        'CK' => 'en',  // Cook Islands -> English
        'CL' => 'es',  // Chile -> Spanish
        'CM' => 'fr',  // Cameroon -> French
        'CN' => 'zh',  // China -> Chinese (Simplified)
        'CO' => 'es',  // Colombia -> Spanish
        'CR' => 'es',  // Costa Rica -> Spanish
        'CU' => 'es',  // Cuba -> Spanish
        'CV' => 'pt',  // Cape Verde -> Portuguese
        'CW' => 'nl',  // Curaçao -> Dutch
        'CX' => 'en',  // Christmas Island -> English
        'CY' => 'el',  // Cyprus -> Greek
        'CZ' => 'cs',  // Czech Republic -> Czech
        'DE' => 'de',  // Germany -> German
        'DJ' => 'fr',  // Djibouti -> French
        'DK' => 'da',  // Denmark -> Danish
        'DM' => 'en',  // Dominica -> English
        'DO' => 'es',  // Dominican Republic -> Spanish
        'DZ' => 'ar',  // Algeria -> Arabic
        'EC' => 'es',  // Ecuador -> Spanish
        'EE' => 'et',  // Estonia -> Estonian
        'EG' => 'ar',  // Egypt -> Arabic
        'EH' => 'ar',  // Western Sahara -> Arabic
        'ER' => 'ti',  // Eritrea -> Tigrinya
        'ES' => 'es',  // Spain -> Spanish
        'ET' => 'am',  // Ethiopia -> Amharic
        'FI' => 'fi',  // Finland -> Finnish
        'FJ' => 'en',  // Fiji -> English
        'FK' => 'en',  // Falkland Islands -> English
        'FM' => 'en',  // Federated States of Micronesia -> English
        'FO' => 'fo',  // Faroe Islands -> Faroese
        'FR' => 'fr',  // France -> French
        'GA' => 'fr',  // Gabon -> French
        'GB' => 'en',  // United Kingdom -> English
        'GD' => 'en',  // Grenada -> English
        'GE' => 'ka',  // Georgia -> Georgian
        'GF' => 'fr',  // French Guiana -> French
        'GG' => 'en',  // Guernsey -> English
        'GH' => 'en',  // Ghana -> English
        'GI' => 'en',  // Gibraltar -> English
        'GL' => 'kl',  // Greenland -> Greenlandic
        'GM' => 'en',  // Gambia -> English
        'GN' => 'fr',  // Guinea -> French
        'GP' => 'fr',  // Guadeloupe -> French
        'GQ' => 'es',  // Equatorial Guinea -> Spanish
        'GR' => 'el',  // Greece -> Greek
        'GS' => 'en',  // South Georgia and the South Sandwich Islands -> English
        'GT' => 'es',  // Guatemala -> Spanish
        'GU' => 'en',  // Guam -> English
        'GW' => 'pt',  // Guinea-Bissau -> Portuguese
        'GY' => 'en',  // Guyana -> English
        'HK' => 'zh',  // Hong Kong -> Chinese (Traditional)
        'HM' => 'en',  // Heard Island and McDonald Islands -> English
        'HN' => 'es',  // Honduras -> Spanish
        'HR' => 'hr',  // Croatia -> Croatian
        'HT' => 'fr',  // Haiti -> French
        'HU' => 'hu',  // Hungary -> Hungarian
        'ID' => 'id',  // Indonesia -> Indonesian
        'IE' => 'en',  // Ireland -> English
        'IL' => 'he',  // Israel -> Hebrew
        'IM' => 'en',  // Isle of Man -> English
        'IN' => 'hi',  // India -> Hindi
        'IO' => 'en',  // British Indian Ocean Territory -> English
        'IQ' => 'ar',  // Iraq -> Arabic
        'IR' => 'fa',  // Iran -> Persian
        'IS' => 'is',  // Iceland -> Icelandic
        'IT' => 'it',  // Italy -> Italian
        'JE' => 'en',  // Jersey -> English
        'JM' => 'en',  // Jamaica -> English
        'JO' => 'ar',  // Jordan -> Arabic
        'JP' => 'ja',  // Japan -> Japanese
        'KE' => 'sw',  // Kenya -> Swahili
        'KG' => 'ky',  // Kyrgyzstan -> Kyrgyz
        'KH' => 'km',  // Cambodia -> Khmer
        'KI' => 'en',  // Kiribati -> English
        'KM' => 'ar',  // Comoros -> Arabic
        'KN' => 'en',  // Saint Kitts and Nevis -> English
        'KP' => 'ko',  // North Korea -> Korean
        'KR' => 'ko',  // South Korea -> Korean
        'KW' => 'ar',  // Kuwait -> Arabic
        'KY' => 'en',  // Cayman Islands -> English
        'KZ' => 'kk',  // Kazakhstan -> Kazakh
        'LA' => 'lo',  // Laos -> Lao
        'LB' => 'ar',  // Lebanon -> Arabic
        'LC' => 'en',  // Saint Lucia -> English
        'LI' => 'de',  // Liechtenstein -> German
        'LK' => 'si',  // Sri Lanka -> Sinhala
        'LR' => 'en',  // Liberia -> English
        'LS' => 'st',  // Lesotho -> Southern Sotho
        'LT' => 'lt',  // Lithuania -> Lithuanian
        'LU' => 'lb',  // Luxembourg -> Luxembourgish
        'LV' => 'lv',  // Latvia -> Latvian
        'LY' => 'ar',  // Libya -> Arabic
        'MA' => 'ar',  // Morocco -> Arabic
        'MC' => 'fr',  // Monaco -> French
        'MD' => 'ro',  // Moldova -> Romanian
        'ME' => 'sr',  // Montenegro -> Serbian
        'MF' => 'fr',  // Saint Martin (French part) -> French
        'MG' => 'mg',  // Madagascar -> Malagasy
        'MH' => 'mh',  // Marshall Islands -> Marshallese
        'MK' => 'mk',  // North Macedonia -> Macedonian
        'ML' => 'bm',  // Mali -> Bambara
        'MM' => 'my',  // Myanmar -> Burmese
        'MN' => 'mn',  // Mongolia -> Mongolian
        'MO' => 'zh',  // Macao -> Chinese (Traditional)
        'MP' => 'en',  // Northern Mariana Islands -> English
        'MQ' => 'fr',  // Martinique -> French
        'MR' => 'ar',  // Mauritania -> Arabic
        'MS' => 'en',  // Montserrat -> English
        'MT' => 'mt',  // Malta -> Maltese
        'MU' => 'fr',  // Mauritius -> French
        'MV' => 'dv',  // Maldives -> Dhivehi
        'MW' => 'ny',  // Malawi -> Chichewa
        'MX' => 'es',  // Mexico -> Spanish
        'MY' => 'ms',  // Malaysia -> Malay
        'MZ' => 'pt',  // Mozambique -> Portuguese
        'NA' => 'en',  // Namibia -> English
        'NC' => 'fr',  // New Caledonia -> French
        'NE' => 'fr',  // Niger -> French
        'NF' => 'en',  // Norfolk Island -> English
        'NG' => 'en',  // Nigeria -> English
        'NI' => 'es',  // Nicaragua -> Spanish
        'NL' => 'nl',  // Netherlands -> Dutch
        'NO' => 'no',  // Norway -> Norwegian
        'NP' => 'ne',  // Nepal -> Nepali
        'NR' => 'na',  // Nauru -> Nauruan
        'NU' => 'niu', // Niue -> Niuean
        'NZ' => 'en',  // New Zealand -> English
        'OM' => 'ar',  // Oman -> Arabic
        'PA' => 'es',  // Panama -> Spanish
        'PE' => 'es',  // Peru -> Spanish
        'PF' => 'fr',  // French Polynesia -> French
        'PG' => 'en',  // Papua New Guinea -> English
        'PH' => 'fil', // Philippines -> Filipino
        'PK' => 'ur',  // Pakistan -> Urdu
        'PL' => 'pl',  // Poland -> Polish
        'PM' => 'fr',  // Saint Pierre and Miquelon -> French
        'PN' => 'en',  // Pitcairn -> English
        'PR' => 'es',  // Puerto Rico -> Spanish
        'PS' => 'ar',  // Palestine -> Arabic
        'PT' => 'pt',  // Portugal -> Portuguese
        'PW' => 'en',  // Palau -> English
        'PY' => 'es',  // Paraguay -> Spanish
        'QA' => 'ar',  // Qatar -> Arabic
        'RE' => 'fr',  // Réunion -> French
        'RO' => 'ro',  // Romania -> Romanian
        'RS' => 'sr',  // Serbia -> Serbian
        'RU' => 'ru',  // Russia -> Russian
        'RW' => 'rw',  // Rwanda -> Kinyarwanda
        'SA' => 'ar',  // Saudi Arabia -> Arabic
        'SB' => 'en',  // Solomon Islands -> English
        'SC' => 'fr',  // Seychelles -> French
        'SD' => 'ar',  // Sudan -> Arabic
        'SE' => 'sv',  // Sweden -> Swedish
        'SG' => 'en',  // Singapore -> English
        'SH' => 'en',  // Saint Helena -> English
        'SI' => 'sl',  // Slovenia -> Slovenian
        'SJ' => 'no',  // Svalbard and Jan Mayen -> Norwegian
        'SK' => 'sk',  // Slovakia -> Slovak
        'SL' => 'en',  // Sierra Leone -> English
        'SM' => 'it',  // San Marino -> Italian
        'SN' => 'fr',  // Senegal -> French
        'SO' => 'so',  // Somalia -> Somali
        'SR' => 'nl',  // Suriname -> Dutch
        'SS' => 'en',  // South Sudan -> English
        'ST' => 'pt',  // Sao Tome and Principe -> Portuguese
        'SV' => 'es',  // El Salvador -> Spanish
        'SX' => 'nl',  // Sint Maarten (Dutch part) -> Dutch
        'SY' => 'ar',  // Syria -> Arabic
        'SZ' => 'ss',  // Eswatini -> Swazi
        'TC' => 'en',  // Turks and Caicos Islands -> English
        'TD' => 'fr',  // Chad -> French
        'TF' => 'fr',  // French Southern and Antarctic Lands -> French
        'TG' => 'fr',  // Togo -> French
        'TH' => 'th',  // Thailand -> Thai
        'TJ' => 'tg',  // Tajikistan -> Tajik
        'TK' => 'tkl', // Tokelau -> Tokelauan
        'TL' => 'pt',  // Timor-Leste -> Portuguese
        'TM' => 'tk',  // Turkmenistan -> Turkmen
        'TN' => 'ar',  // Tunisia -> Arabic
        'TO' => 'to',  // Tonga -> Tongan
        'TR' => 'tr',  // Turkey -> Turkish
        'TT' => 'en',  // Trinidad and Tobago -> English
        'TV' => 'en',  // Tuvalu -> English
        'TW' => 'zh',  // Taiwan -> Chinese (Traditional)
        'TZ' => 'sw',  // Tanzania -> Swahili
        'UA' => 'uk',  // Ukraine -> Ukrainian
        'UG' => 'sw',  // Uganda -> Swahili
        'UM' => 'en',  // United States Minor Outlying Islands -> English
        'US' => 'en',  // United States -> English
        'UY' => 'es',  // Uruguay -> Spanish
        'UZ' => 'uz',  // Uzbekistan -> Uzbek
        'VA' => 'it',  // Vatican City -> Italian
        'VC' => 'en',  // Saint Vincent and the Grenadines -> English
        'VE' => 'es',  // Venezuela -> Spanish
        'VG' => 'en',  // British Virgin Islands -> English
        'VI' => 'en',  // U.S. Virgin Islands -> English
        'VN' => 'vi',  // Vietnam -> Vietnamese
        'VU' => 'bi',  // Vanuatu -> Bislama
        'WF' => 'fr',  // Wallis and Futuna -> French
        'WS' => 'sm',  // Samoa -> Samoan
        'YE' => 'ar',  // Yemen -> Arabic
        'YT' => 'fr',  // Mayotte -> French
        'ZA' => 'en',  // South Africa -> English
        'ZM' => 'en',  // Zambia -> English
        'ZW' => 'en',  // Zimbabwe -> English
    ]
];