@extends('developer.menu')

@section('content')
    <h1>Gift Card Guide</h1>
    <p class="lead-text">
        Learn how to discover gift cards, calculate the customer price, place an order, and deliver redemption details after confirmation.
    </p>

    <p><a href="{{ route('developer.guides') }}">&larr; Back to all guides</a></p>

    <h2 id="how-the-flow-works">How the Flow Works</h2>
    <ol>
        <li>Choose a supported country.</li>
        <li>List the gift cards available in that country.</li>
        <li>Inspect the selected card's denomination rules and limits.</li>
        <li>Request a quote for the selected amount.</li>
        <li>Create the order with a unique external reference.</li>
        <li>Wait for the final webhook before delivering the redemption details.</li>
    </ol>

    <h2 id="step-1-discover-cards">1. Discover Available Cards</h2>
    <p>
        Start with <a href="{{ route('developer.countries') }}">List Countries</a>. Pass the selected country's two-letter ISO2 code to <a href="{{ route('developer.card.all') }}">List Gift Cards</a>, then use <a href="{{ route('developer.card.single') }}">Get Gift Card</a> to read the card's currency, minimum, maximum, available denominations, and redemption instructions.
    </p>

    <div class="info-box note">
        <div class="info-box-title">
            <i class="bi bi-info-circle"></i>
            Store the Card ID
        </div>
        <p>
            Save the returned card ID in your catalogue. Use that ID for both the quote and order requests. Refresh your catalogue periodically because availability and denomination rules can change.
        </p>
    </div>

    <h2 id="step-2-request-a-quote">2. Request a Quote</h2>
    <p>
        Call <a href="{{ route('developer.card.quote') }}">Create Gift Card Quote</a> with the card ID and face value. Show the returned currency, exchange rate, charge, and total to the customer before placing the order.
    </p>

    <div class="code-block-wrapper">
        <div class="code-block-header">
            <span class="code-block-title">Quote Request</span>
            <button class="code-copy-button">Copy</button>
        </div>
        <pre><code class="language-bash">curl -X POST "{{ url('/') }}/api/v1/giftcard-quote" \
  -H "Authorization: Bearer sk_test_your_api_key" \
  -H "Idempotency-Key: giftcard-quote-1001" \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
  -d '{
    "card_id": "cf562d2a-826c-42f1-a19f-3de7fe6911c0",
    "amount": 25
  }'</code></pre>
    </div>

    <h2 id="step-3-create-the-order">3. Create the Order</h2>
    <p>
        The <a href="{{ route('developer.card.order') }}">Order Gift Card</a> endpoint accepts a <code>data</code> array, so you can submit one or more order items. Give every item a unique <code>external_reference</code> generated by your application.
    </p>

    <div class="code-block-wrapper">
        <div class="code-block-header">
            <span class="code-block-title">Order Request</span>
            <button class="code-copy-button">Copy</button>
        </div>
        <pre><code class="language-bash">curl -X POST "{{ url('/') }}/api/v1/giftcard-order" \
  -H "Authorization: Bearer sk_test_your_api_key" \
  -H "Idempotency-Key: giftcard-order-1001" \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
  -d '{
    "data": [
      {
        "external_reference": "customer-order-1001",
        "card_id": "cf562d2a-826c-42f1-a19f-3de7fe6911c0",
        "quantity": 1,
        "amount": 25,
        "name": "Jane Doe",
        "email": "jane@example.com",
        "phone": "+12025550136",
        "phone_code": "US"
      }
    ]
  }'</code></pre>
    </div>

    <h2 id="step-4-confirm-and-deliver">4. Confirm and Deliver</h2>
    <p>
        Treat the order response as acknowledgement that processing has started. Process the <code>giftcard</code> webhook and deliver the redemption code or URL only after the transaction reaches a successful final status.
    </p>
    <p>
        Store each webhook before acting on it. If the same event or transaction status arrives again, return success without delivering the card twice. Use <a href="{{ route('developer.card.transaction') }}">Get Gift Card Transaction</a> or <a href="{{ route('developer.card.transactions') }}">List Gift Card Transactions</a> for reconciliation.
    </p>

    <div class="info-box warning">
        <div class="info-box-title">
            <i class="bi bi-exclamation-triangle"></i>
            Redemption Details Are Sensitive
        </div>
        <p>
            Treat card codes, PINs, and redemption URLs like cash. Do not write them to ordinary application logs, analytics events, or error-reporting tools.
        </p>
    </div>

    <h2 id="production-checklist">Production Checklist</h2>
    <ul>
        <li>Validate the card amount against its denomination rules.</li>
        <li>Display the quote currency and final total clearly.</li>
        <li>Use a unique external reference for every order item.</li>
        <li>Handle partial success when submitting more than one item.</li>
        <li>Verify webhook signatures and make delivery idempotent.</li>
        <li>Test failed, pending, and successful outcomes in sandbox.</li>
    </ul>

    <div class="info-box success">
        <div class="info-box-title">
            <i class="bi bi-check-circle"></i>
            Related Documentation
        </div>
        <p>
            See <a href="{{ route('developer.card.all') }}">Gift Card API Reference</a> and <a href="{{ route('developer.webhook') }}">Webhooks</a> for full request fields, responses, and event payloads.
        </p>
    </div>
@endsection
