<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Services\Cachable\ModelCaching\Traits\Cachable;

class Settings extends Model {
    use Cachable;
    protected $table = "settings";
    protected $fillable = [
        'min_rga', 
        'min_ega', 
        'rga', 
        'ega', 
        'rss', 
        'ess', 
        'dss', 
        'scs', 
        'egi', 
        'dsi', 
        'egg', 
        'dgg', 
        'title',
        'site_name',
        'site_desc',
        'address',
        'email',
        'support_email',
        'recovery_email',
        'mobile',
        'livechat',
        'recaptcha',
        'email_template',
        'default_font',
        'analytic_snippet',
        'admin_url',
        'registration',
        'email_notify',
        'language',
        'maintenance',
        'career_url',
        'NOCAPTCHA_SECRET',
        'NOCAPTCHA_SITEKEY',
        'timezone',
        'otp',
        'xperiod',
        'terms',
        'privacy',
        'about',
        'google_sl',
        'google_ci',
        'google_cs',
        'facebook_sl',
        'facebook_ci',
        'facebook_cs',
        'email_verify',
        'phone_verify',
        'routing_type',
        'payout',
        'min_pl',
        'max_pl',
        'min_account',
        'max_account',
        'withdraw_fiat_pc',
        'withdraw_percent_pc',
        'withdraw_pct',        
        'deposit_fiat_pc',
        'deposit_percent_pc',
        'deposit_pct',
        'money_transfer',
        'min_tl',
        'max_tl',
        'fiat_tc',
        'percent_tc',
        'tct',
        'twilio_number',
        'twilio_account_sid',
        'twilio_auth_token',
        'dp_bank_name',
        'bk_routing_code',
        'bk_routing_type',
        'bk_acct_no',
        'bk_acct_name',
        'bk_status',
        'currency_format',
        'savings',
        'otp_login',
        'otp_beneficiary',
        'otp_bank',
        'otp_type',
        'otp_withdraw',
        'otp_expire_time',
        'otp_expire_duration',
        'otp_resend_time',
        'otp_resend_duration',
        'email_banned',
        'admin_language',
        'user_language',
        'admin_timezone',
        'firewall',
        'cl_api_key',
        'cl_api_mode',
        'currency_layer',
        'file_upload_size',
        'files_allowed',
        'currency',
        'api_throttling',
        'preloader',
        'preloader_color',
        'giftcard_sell',
        'giftcard_buy',
        'team',
        'brands',
        'reviews',
        'services',
        'images_allowed',
        'redboxx_low_notify'
    ];

    public function real()
    {
        return $this->belongsTo(Country::class, 'currency');
    }   
}
