@extends('developer.reference.menu')

@section('content')
    <h1>{{ $title }}</h1>
    <p class="lead-text">Creates one or more gift card orders</p>

    <div class="endpoint-box">
        <span class="endpoint-method get">POST</span>
        <span class="endpoint-url">{{ url('/') }}/api/v1/giftcard-order</span>
    </div>

    <h2 id="request-parameters">Body Parameters</h2>

    <table class="params-table">
        <thead>
        <tr>
            <th>Parameter</th>
            <th>Type</th>
            <th>Required</th>
            <th>Description</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><span class="param-name">data</span></td>
            <td><span class="param-type">array</span></td>
            <td>required</td>
            <td>
                An array of gift card order objects. Each object represents one gift card order to be created.
            </td>
        </tr>
        <tr>
            <td><span class="param-name">data.*.external_reference</span></td>
            <td><span class="param-type">string</span></td>
            <td>required</td>
            <td>
                A unique reference generated by your system for tracking the order. This helps prevent duplicate processing and makes reconciliation easier.
            </td>
        </tr>
        <tr>
            <td><span class="param-name">data.*.card_id</span></td>
            <td><span class="param-type">string</span></td>
            <td>required</td>
            <td>The ID of the gift card to order.</td>
        </tr>
        <tr>
            <td><span class="param-name">data.*.quantity</span></td>
            <td><span class="param-type">integer</span></td>
            <td>required</td>
            <td>
                The number of gift cards to order for this item. The maximum allowed quantity is 10 per order item.
            </td>
        </tr>
        <tr>
            <td><span class="param-name">data.*.amount</span></td>
            <td><span class="param-type">numeric</span></td>
            <td>required</td>
            <td>The amount/value of each gift card.</td>
        </tr>
        <tr>
            <td><span class="param-name">data.*.name</span></td>
            <td><span class="param-type">string</span></td>
            <td>required</td>
            <td>The name of the recipient.</td>
        </tr>
        <tr>
            <td><span class="param-name">data.*.email</span></td>
            <td><span class="param-type">string</span></td>
            <td>required</td>
            <td>The email address of the recipient.</td>
        </tr>
        <tr>
            <td><span class="param-name">data.*.phone</span></td>
            <td><span class="param-type">string</span></td>
            <td>required</td>
            <td>The phone number of the recipient.</td>
        </tr>
        <tr>
            <td><span class="param-name">data.*.phone_code</span></td>
            <td><span class="param-type">string</span></td>
            <td>required</td>
            <td>
                Recipient phone country code using the country ISO2 format, for example: US, NG, ZW.
            </td>
        </tr>
        </tbody>
    </table>

    <h2 id="example-request">Example Request</h2>

    <h3 id="create-gift-card-orders">Create gift card orders</h3>

    <div class="code-block-wrapper">
        <div class="code-block-header">
            <span class="code-block-title">cURL</span>
            <button class="code-copy-button">Copy</button>
        </div>
        <pre><code class="language-bash">curl -X POST {{ url('/') }}/api/v1/giftcard-order \
  -H "Authorization: Bearer sk_live_your_api_key" \
  -H "Content-Type: application/json" \
  -d '{
    "data": [
      {
        "external_reference": "order-ref-001",
        "card_id": "cf562d2a-826c-42f1-a19f-3de7fe6911c0",
        "quantity": 4,
        "amount": 11,
        "email": "name@remote.com",
        "phone": "+12025550136",
        "phone_code": "US",
        "name": "John Doe"
      },
      {
        "external_reference": "order-ref-002",
        "card_id": "d96096ad-1eff-4e38-afd0-7d02973d4b5f",
        "quantity": 3,
        "amount": 20,
        "email": "name@remote.com",
        "phone": "+12025550136",
        "phone_code": "US",
        "name": "John Doe"
      }
    ]
  }'</code></pre>
    </div>

    <div class="code-block-wrapper">
        <div class="code-block-header">
            <span class="code-block-title">PHP</span>
            <button class="code-copy-button">Copy</button>
        </div>
        <pre><code class="language-php">$client = new GuzzleHttp\Client([
    'base_uri' => '{{ url('/') }}/api/v1',
    'headers' => [
        'Authorization' => 'Bearer sk_live_your_api_key',
        'Content-Type' => 'application/json',
        'Accept' => 'application/json',
    ],
]);

$response = $client->post('/giftcard-order', [
    'json' => [
        'data' => [
            [
                'external_reference' => 'order-ref-001',
                'card_id' => 'cf562d2a-826c-42f1-a19f-3de7fe6911c0',
                'quantity' => 4,
                'amount' => 11,
                'email' => 'name@remote.com',
                'phone' => '+12025550136',
                'phone_code' => 'US',
                'name' => 'John Doe',
            ],
            [
                'external_reference' => 'order-ref-002',
                'card_id' => 'd96096ad-1eff-4e38-afd0-7d02973d4b5f',
                'quantity' => 3,
                'amount' => 20,
                'email' => 'name@remote.com',
                'phone' => '+12025550136',
                'phone_code' => 'US',
                'name' => 'John Doe',
            ],
        ],
    ],
]);

$orders = json_decode($response->getBody(), true);</code></pre>
    </div>

    <div class="code-block-wrapper">
        <div class="code-block-header">
            <span class="code-block-title">JavaScript</span>
            <button class="code-copy-button">Copy</button>
        </div>
        <pre><code class="language-javascript">const response = await fetch('{{ url('/') }}/api/v1/giftcard-order', {
  method: 'POST',
  headers: {
    'Authorization': 'Bearer sk_live_your_api_key',
    'Content-Type': 'application/json',
    'Accept': 'application/json'
  },
  body: JSON.stringify({
    data: [
      {
        external_reference: 'order-ref-001',
        card_id: 'cf562d2a-826c-42f1-a19f-3de7fe6911c0',
        quantity: 4,
        amount: 11,
        email: 'name@remote.com',
        phone: '+12025550136',
        phone_code: 'US',
        name: 'John Doe'
      },
      {
        external_reference: 'order-ref-002',
        card_id: 'd96096ad-1eff-4e38-afd0-7d02973d4b5f',
        quantity: 3,
        amount: 20,
        email: 'name@remote.com',
        phone: '+12025550136',
        phone_code: 'US',
        name: 'John Doe'
      }
    ]
  })
});

const orders = await response.json();</code></pre>
    </div>

    <h2 id="response">Response</h2>

    <div class="code-block-wrapper">
        <div class="code-block-header">
            <span class="code-block-title">200 OK</span>
            <button class="code-copy-button">Copy</button>
        </div>
        <pre><code class="language-json">{
   "message": "Payment successful, processing order",
    "status": "success",
    "data": {
        "id": "3f03fd72-1836-4880-912c-c45b4eb016cc",
        "currency": "USD",
        "amount": 124.56,
        "charge": 10.44,
        "total": 135,
        "status": "success",
        "mode": "test",
        "balance": {
            "old_balance": 0,
            "new_balance": 0
        },
        "orders": [
            {
                "external_reference": "50d1251a-d262-41ba-aed0-8cef37af9d3e",
                "card": {
                    "id": "cf562d2a-826c-42f1-a19f-3de7fe6911c0",
                    "name": "App Store & iTunes US",
                    "quantity": 4,
                    "amount": 11,
                    "currency": "USD"
                },
                "payment": {
                    "currency": "USD",
                    "rate": 1,
                    "amount": 11,
                    "charge": 1,
                    "sub_total": 12,
                    "total": 48
                },
                "customer": {
                    "name": "John Doe",
                    "email": "name@remote.com",
                    "phone": "+12025550136",
                    "phone_code": "US"
                },
                "items": [
                    {
                        "id": "3084a8dd-47d7-443a-a14d-a06b1fb18e6e",
                        "status": "pending",
                        "redeem_code": {
                            "url": null,
                            "card_code": null,
                            "pin": null
                        }
                    },
                    {
                        "id": "5c3cbb21-e43f-4e1c-a61a-81c0c19bab60",
                        "status": "pending",
                        "redeem_code": {
                            "url": null,
                            "card_code": null,
                            "pin": null
                        }
                    },
                    {
                        "id": "8a4b7c36-572b-48b7-9aa3-5adc45e646fc",
                        "status": "pending",
                        "redeem_code": {
                            "url": null,
                            "card_code": null,
                            "pin": null
                        }
                    },
                    {
                        "id": "e748d5a8-0907-40f4-a3ed-4d5eea8b4ce3",
                        "status": "pending",
                        "redeem_code": {
                            "url": null,
                            "card_code": null,
                            "pin": null
                        }
                    }
                ]
            },
            {
                "external_reference": "36a1ac5a-07d5-44ef-90f5-51a3a1d1348b",
                "card": {
                    "id": "d96096ad-1eff-4e38-afd0-7d02973d4b5f",
                    "name": "H Samuel",
                    "quantity": 3,
                    "amount": 20,
                    "currency": "GBP"
                },
                "payment": {
                    "currency": "USD",
                    "rate": 1.3425882416122,
                    "amount": 26.85,
                    "charge": 2.15,
                    "sub_total": 29,
                    "total": 87
                },
                "customer": {
                    "name": "John Doe",
                    "email": "name@remote.com",
                    "phone": "+12025550136",
                    "phone_code": "US"
                },
                "items": [
                    {
                        "id": "6991178f-57b6-417c-a78a-e862fa51568a",
                        "status": "pending",
                        "redeem_code": {
                            "url": null,
                            "card_code": null,
                            "pin": null
                        }
                    },
                    {
                        "id": "ccf88760-2335-4204-a843-32b38f02fe5a",
                        "status": "pending",
                        "redeem_code": {
                            "url": null,
                            "card_code": null,
                            "pin": null
                        }
                    },
                    {
                        "id": "e9248e6f-e4db-4d06-8467-e6234ad254a8",
                        "status": "pending",
                        "redeem_code": {
                            "url": null,
                            "card_code": null,
                            "pin": null
                        }
                    }
                ]
            }
        ],
        "created_at": "2026-05-05T13:19:22.000000Z"
    }
}</code></pre>
    </div>
@endsection